apiVersion: apps/v1
kind: Deployment
metadata:
  name: marketplace-service
  labels:
    app: marketplace-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: marketplace-service
  template:
    metadata:
      labels:
        app: marketplace-service
    spec:
      containers:
        - name: marketplace-service
          image: marketplace-service:1.0
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m # Resource requests for the pod
              memory: 256Mi
            limits:
              cpu: 1000m # Resource limits for the pod
              memory: 512Mi