apiVersion: v1
kind: Service
metadata:
  name: marketplace-service
spec:
  type: ClusterIP
  selector:
    app: marketplace-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

